wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.18
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.12
    start_time: 1655481111
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 2
      - 15
      4: 3.9.12
      5: 0.12.18
      8:
      - 5
batch_size:
  desc: null
  value: 25000
early_loss_mean:
  desc: null
  value: true
erm_amount:
  desc: null
  value: 1.0
eval_interval:
  desc: null
  value: 100
grayscale_model:
  desc: null
  value: false
hidden_dim:
  desc: null
  value: 256
l2_regularizer_weight:
  desc: null
  value: 0.001
lr:
  desc: null
  value: 0.001
mse:
  desc: null
  value: true
n_restarts:
  desc: null
  value: 10
p:
  desc: null
  value: 1.0
penalty_anneal_iters:
  desc: null
  value: 100
penalty_weight:
  desc: null
  value: 10000.0
plot:
  desc: null
  value: true
plot_fig5_irm_paper:
  desc: null
  value: false
print_eval_intervals:
  desc: null
  value: true
rex:
  desc: null
  value: true
save_numpy_log:
  desc: null
  value: true
shift:
  desc: null
  value: shift_spurious_x
steps:
  desc: null
  value: 501
test_env__color_noise:
  desc: null
  value: 0.9
test_prob_class_0:
  desc: null
  value: 0.5
train_env_1__color_noise:
  desc: null
  value: 0.2
train_env_2__color_noise:
  desc: null
  value: 0.1
train_set_size:
  desc: null
  value: 50000
use_wandb:
  desc: null
  value: true
wandb_project:
  desc: null
  value: cs_hparam_tuning_2
wandb_tag:
  desc: null
  value: irm_hparams__stable_x_shift
